"""Single source of truth for notebook sizes (all values in mm).

Imported by both generators; `write_sizes_tex()` emits `sizes.tex` for the
LaTeX templates. Edit sizes here — never hand-edit sizes.tex.
"""

from pathlib import Path

# ── Page geometry + red margin (consumed by LaTeX templates via \Size) ──
SIZES = {
    "cozyca": {"pw": 100, "ph": 90, "red_line": 8},
    "m5": {"pw": 67, "ph": 105, "red_line": 13},
    "m5l": {"pw": 105, "ph": 67, "red_line": 8},  # landscape m5 (senary)
    "a5s": {"pw": 110, "ph": 210, "red_line": 12},
}

# ── Design-specific layout params (consumed only by the generators) ──
NIGHTOWL = {
    "cozyca": {"binding": 15, "right_margin": 3, "row_gap": 7.5, "num_gap": 16},
    "m5": {"binding": 12, "right_margin": 3, "row_gap": 8.0, "num_gap": 11},
}
XIANZHANG = {"cozyca": 9, "m5": 9, "a5s": 12}  # top_gap: ruling start from top


def write_sizes_tex(path: Path = Path("sizes.tex")) -> None:
    """Emit sizes.tex exposing PW, PH, RedLine per size for the templates."""
    lines = [
        r"% Generated by sizes.py — do not edit; edit sizes.py",
        r"\def\Size#1#2{\csname size@#1@#2\endcsname}",
    ]
    for key, s in SIZES.items():
        for field, val in (
            ("PW", s["pw"]),
            ("PH", s["ph"]),
            ("RedLine", s["red_line"]),
        ):
            lines.append(
                rf"\expandafter\def\csname size@{key}@{field}\endcsname{{{val}}}"
            )
    path.write_text("\n".join(lines) + "\n")


if __name__ == "__main__":
    write_sizes_tex()
    print("Generated sizes.tex")
