"""Single source of truth for notebook sizes (mm) and fonts (pt).

Imported by both generators; `write_sizes_tex()` emits `sizes.tex` for the
LaTeX templates. Edit sizes here — never hand-edit sizes.tex.
"""

import subprocess
from pathlib import Path

# ── Page geometry + red margin (consumed by LaTeX templates via \Size) ──
SIZES = {
    "cozyca": {"pw": 100, "ph": 90, "red_line": 8},
    "m5": {"pw": 67, "ph": 105, "red_line": 13},
    "m5l": {"pw": 105, "ph": 67, "red_line": 8},  # landscape m5 (senary)
    "a5s": {"pw": 110, "ph": 210, "red_line": 12},
}

# ── Design-specific layout params (consumed only by the generators) ──
NIGHTOWL = {
    "cozyca": {"binding": 15, "right_margin": 3, "row_gap": 7.5, "num_gap": 16},
    "m5": {"binding": 12, "right_margin": 3, "row_gap": 8.0, "num_gap": 11},
}
XIANZHANG = {"cozyca": 9, "m5": 9, "a5s": 12}  # top_gap: ruling start from top

# ── Font sizes in pt ──
FONTS = {
    "large": 12,
    "medium": 9,
    "small": 8,
    "tiny": 5,
}

FONT_CMD = {k: f"Font{k.title()}" for k in FONTS}


def write_sizes_tex(path: Path | None = None) -> None:
    """Emit sizes.tex exposing page sizes, red lines, and font commands."""
    if path is None:
        path = Path(__file__).parent / "sizes.tex"
    lines = [
        r"% Generated by sizes.py — do not edit; edit sizes.py",
        r"\def\Size#1#2{\csname size@#1@#2\endcsname}",
    ]
    for key, s in SIZES.items():
        for field, val in (
            ("PW", s["pw"]),
            ("PH", s["ph"]),
            ("RedLine", s["red_line"]),
        ):
            lines.append(
                rf"\expandafter\def\csname size@{key}@{field}\endcsname{{{val}}}"
            )
    lines.append("")
    lines.append(r"% Font size commands (pt / leading)")
    for key, size in FONTS.items():
        leading = size * 1.2
        lines.append(
            rf"\def\{FONT_CMD[key]}"
            rf"{{\fontsize{{{size}pt}}{{{leading:.1f}pt}}\selectfont}}"
        )
    path.write_text("\n".join(lines) + "\n")


def compile(tex_file: str, cwd: Path) -> None:
    """Run xelatex twice."""
    for _ in range(2):
        subprocess.run(["xelatex", tex_file], cwd=cwd, check=True)


if __name__ == "__main__":
    write_sizes_tex()
    print("Generated sizes.tex")
