"""Single source of truth for notebook sizes (mm) and fonts (pt).

Imported by both generators; `write_sizes_tex()` emits `sizes.tex` for the
LaTeX templates. Edit sizes here — never hand-edit sizes.tex.
"""

import subprocess
from pathlib import Path

# ── Page geometry + red margin (consumed by LaTeX templates via \Size) ──
SIZES = {
    "cozyca": {"pw": 100, "ph": 90, "red_line": 8},
    "m5": {"pw": 67, "ph": 105, "red_line": 13},
    "74m5": {"pw": 74, "ph": 105, "red_line": 12},
    "m5l": {"pw": 105, "ph": 67, "red_line": 8},  # landscape m5 (senary)
    "a5s": {"pw": 148, "ph": 210, "red_line": 15},
    "tn": {"pw": 110, "ph": 210, "red_line": 15},
}

# ── Design-specific layout params (consumed only by the generators) ──
SEYES = {
    "tn": {
        "binding": 12,
        "outer_margin": 5,
        "top_margin": 10,
        "bottom_margin": 10,
        "row_height": 2,
        "group_size": 4,
        "thick_line": 0.3,
        "thin_line": 0.1,
        "red_line_width": 0.3,
    },
}

LINEAR = {
    "a5s": {
        "binding": 15,
        "right_margin": 5,
        "top_margin": 10,
        "bottom_margin": 10,
        "line_gap": 7,
        "line_width": 2,
    },
}

NIGHTOWL = {
    "cozyca": {"binding": 15, "right_margin": 3, "row_gap": 7.5, "num_gap": 16},
    "m5": {"binding": 12, "right_margin": 3, "row_gap": 8.0, "num_gap": 11},
    "74m5": {"binding": 12, "right_margin": 3, "row_gap": 8.0, "num_gap": 13},
    "a5s": {"binding": 18, "right_margin": 5, "row_gap": 14.0, "num_gap": 26},
}

MIDORI_GRID = {
    "cozyca": {
        "binding": 15,
        "right_margin": 3,
        "top_margin": 5,
        "bottom_margin": 5,
        "grid_step": 5,
        "dot_freq": 5,
        "gap_size": 1.2,
        "edge_extension": 1.5,
    },
    "m5": {
        "binding": 12,
        "right_margin": 3,
        "top_margin": 5,
        "bottom_margin": 5,
        "grid_step": 4,
        "dot_freq": 5,
        "gap_size": 1.0,
        "edge_extension": 1.2,
    },
    "74m5": {
        "binding": 12,
        "right_margin": 3,
        "top_margin": 5,
        "bottom_margin": 5,
        "grid_step": 4,
        "dot_freq": 5,
        "gap_size": 1.0,
        "edge_extension": 1.2,
    },
    "m5l": {
        "binding": 10,
        "right_margin": 5,
        "top_margin": 5,
        "bottom_margin": 5,
        "grid_step": 5,
        "dot_freq": 5,
        "gap_size": 1.2,
        "edge_extension": 1.5,
    },
    "a5s": {
        "binding": 15,
        "right_margin": 5,
        "top_margin": 10,
        "bottom_margin": 10,
        "grid_step": 5,
        "dot_freq": 10,
        "gap_size": 1.2,
        "edge_extension": 1.5,
    },
    "tn": {
        "binding": 12,
        "right_margin": 5,
        "top_margin": 10,
        "bottom_margin": 10,
        "grid_step": 5,
        "dot_freq": 10,
        "gap_size": 1.2,
        "edge_extension": 1.5,
    },
}

# ── Font sizes in pt ──
FONTS = {
    "large": 12,
    "medium": 9,
    "small": 8,
    "tiny": 5,
}

# ── Colors (single source of truth, emitted to sizes.tex) ──
COLORS = {
    "IronOxideRed": "8b0000",
    "ChromeYellow": "ffa700",
    "CobaltBlue": "0047ab",
    "NeonGreen": "39FF14",
}

FONT_CMD = {k: f"Font{k.title()}" for k in FONTS}


def write_sizes_tex(path: Path | None = None) -> None:
    """Emit sizes.tex exposing page sizes, red lines, and font commands."""
    if path is None:
        path = Path(__file__).parent / "sizes.tex"
    lines = [
        r"% Generated by sizes.py — do not edit; edit sizes.py",
        r"\def\Size#1#2{\csname size@#1@#2\endcsname}",
    ]
    for key, s in SIZES.items():
        for field, val in (
            ("PW", s["pw"]),
            ("PH", s["ph"]),
            ("RedLine", s["red_line"]),
        ):
            lines.append(
                rf"\expandafter\def\csname size@{key}@{field}\endcsname{{{val}}}"
            )
    lines.append("")
    lines.append(r"% Font size commands (pt / leading)")
    for key, size in FONTS.items():
        leading = size * 1.2
        lines.append(
            rf"\def\{FONT_CMD[key]}"
            rf"{{\fontsize{{{size}pt}}{{{leading:.1f}pt}}\selectfont}}"
        )
    path.write_text("\n".join(lines) + "\n")
    write_colors_tex()


def write_colors_tex(path: Path | None = None) -> None:
    r"""Emit colors.tex with \definecolor for every color in COLORS."""
    if path is None:
        path = Path(__file__).parent / "colors.tex"
    lines = [r"% Generated by sizes.py — do not edit; edit sizes.py"]
    for name, hex_val in COLORS.items():
        lines.append(rf"\definecolor{{{name}}}{{HTML}}{{{hex_val}}}")
    path.write_text("\n".join(lines) + "\n")


def compile(tex_file: str, cwd: Path) -> None:
    """Run xelatex twice."""
    for _ in range(2):
        subprocess.run(["xelatex", tex_file], cwd=cwd, check=True)


if __name__ == "__main__":
    write_sizes_tex()
    print("Generated sizes.tex")
